apiVersion: cnp.3istor.com/v1alpha1
kind: ProjectRecord
metadata:
  name: test-secu
  owner: brian.perret
  createdAt: '2026-10-07T11:04:05.160250+00:00'
spec:
  targetCloud: onprem
  status: active
  environments:
  - name: prod
  apps:
  - name: test-app-secu
    type: static
    repoURL: https://github.com/3-Istor/test-app-secu
    hostnames:
      prod: test-app-secu-test-secu.3istor.com
  - name: test-app-secu-2
    type: static
    repoURL: https://github.com/3-Istor/test-app-secu-2
    hostnames:
      prod: test-app-secu-2-test-secu.3istor.com
  features:
    gatus: true
    offhoursGuard: true
    gateway: true
    tunnel: true
