apiVersion: cnp.3istor.com/v1alpha1
kind: ProjectRecord
metadata:
  name: test-20
  owner: brian.perret
  createdAt: '2026-10-07T15:47:14.125291+00:00'
spec:
  targetCloud: onprem
  status: active
  environments:
  - name: prod
  apps: []
  features:
    gatus: true
    offhoursGuard: true
    gateway: true
    tunnel: true
