apiVersion: cnp.3istor.com/v1alpha1
kind: ProjectRecord
metadata:
  name: test-project-v4
  owner: brian.perret
  createdAt: '2026-09-23T14:53:05.023606+00:00'
spec:
  targetCloud: onprem
  status: active
  environments:
  - name: prod
  apps: []
  features:
    gatus: true
    offhoursGuard: true
