apiVersion: cnp.3istor.com/v1alpha1
kind: ProjectRecord
metadata:
  name: test2
  owner: arthur.presle
  createdAt: '2026-09-21T14:04:14.132060+00:00'
spec:
  targetCloud: onprem
  status: active
  environments:
  - name: prod
  apps: []
  features:
    gatus: true
    offhoursGuard: true
