apiVersion: cnp.3istor.com/v1alpha1
kind: ProjectRecord
metadata:
  name: test-project-v7
  owner: brian.perret
  createdAt: '2026-09-24T10:08:17.379515+00:00'
spec:
  targetCloud: onprem
  status: active
  environments:
  - name: prod
  apps: []
  features:
    gatus: true
    offhoursGuard: true
    gateway: true
    tunnel: true
