apiVersion: cnp.3istor.com/v1alpha1
kind: ProjectRecord
metadata:
  name: test-project-v5
  owner: brian.perret
  createdAt: '2026-09-24T07:35:32.723298+00:00'
spec:
  targetCloud: onprem
  status: active
  environments:
  - name: prod
  apps:
  - name: test-app-v2
    type: static
    repoURL: https://github.com/3-Istor/test-app-v2.git
    hostnames:
      prod: test-app-v2-test-project-v5.3istor.com
  - name: test-app-v3
    type: static
    repoURL: https://github.com/3-Istor/test-app-v3
    hostnames:
      prod: test-app-v3-test-project-v5.3istor.com
  features:
    gatus: true
    offhoursGuard: true
    gateway: true
    tunnel: true
