apiVersion: cnp.3istor.com/v1alpha1
kind: ProjectRecord
metadata:
  name: test-e2e
  owner: brian.perret
  createdAt: '2026-10-06T14:49:41.059475+00:00'
spec:
  targetCloud: onprem
  status: active
  environments:
  - name: prod
  apps: []
  features:
    gatus: true
    offhoursGuard: true
    gateway: true
    tunnel: true
