apiVersion: cnp.3istor.com/v1alpha1
kind: ProjectRecord
metadata:
  name: test-secu-2
  owner: brian.perret
  createdAt: '2026-10-10T13:19:00.680813+00:00'
spec:
  targetCloud: onprem
  status: active
  environments:
  - name: prod
  apps:
  - name: app-secu-1
    type: fullstack
    repoURL: https://github.com/3-Istor/app-secu-1
    hostnames:
      prod: app-secu-1-test-secu-2.3istor.com
  features:
    gatus: true
    offhoursGuard: true
    gateway: true
    tunnel: true
